CREATE TABLE public.achievements
(
    id          integer               NOT NULL,
    description character varying(255),
    name        character varying(45) NOT NULL
);

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.audit_log_types
(
    id          integer               NOT NULL,
    description character varying(255),
    type        character varying(45) NOT NULL
);

ALTER TABLE public.audit_log_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.audit_logs
(
    uuid              uuid                   NOT NULL,
    created_at        timestamp(6) without time zone,
    description       character varying(255) NOT NULL,
    audit_log_type_id integer,
    users_uuid        uuid
);

CREATE TABLE public.generated_paysafe
(
    uuid                uuid                         NOT NULL,
    created_at          timestamp(6) without time zone,
    amount              numeric(10, 2) DEFAULT 0     NOT NULL,
    is_redeemed         boolean        DEFAULT false NOT NULL,
    paysafe_number_hash character varying(255)       NOT NULL,
    redeemed_at         timestamp(6) without time zone,
    valid_till          timestamp(6) without time zone NOT NULL,
    paysafe_state_id    integer
);

CREATE TABLE public.paysafe_log
(
    uuid                   uuid NOT NULL,
    created_at             timestamp(6) without time zone,
    generated_paysafe_uuid uuid,
    new_paysafe_state      integer,
    old_paysafe_state      integer,
    user_uuid              uuid
);

CREATE TABLE public.paysafe_states
(
    id    integer                NOT NULL,
    state character varying(100) NOT NULL
);

ALTER TABLE public.paysafe_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paysafe_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.roles
(
    id   integer               NOT NULL,
    name character varying(45) NOT NULL
);

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transaction_logs
(
    uuid                     uuid NOT NULL,
    created_at               timestamp(6) without time zone,
    new_transaction_state_id integer,
    old_transaction_state_id integer,
    transaction_uuid         uuid,
    user_uuid                uuid
);

CREATE TABLE public.transaction_states
(
    id    integer                NOT NULL,
    state character varying(100) NOT NULL
);

ALTER TABLE public.transaction_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transactions
(
    uuid                   uuid                     NOT NULL,
    created_at             timestamp(6) without time zone,
    amount                 numeric(10, 2) DEFAULT 0 NOT NULL,
    generated_paysafe_uuid uuid,
    transaction_state_id   integer,
    user_uuid              uuid
);

CREATE TABLE public.user_achievements
(
    created_at     timestamp(6) without time zone NOT NULL,
    achievement_id integer NOT NULL,
    user_uuid      uuid    NOT NULL
);

CREATE TABLE public.users
(
    uuid          uuid                   NOT NULL,
    created_at    timestamp(6) without time zone,
    balance       numeric(10, 2)         NOT NULL,
    date_of_birth date                   NOT NULL,
    email         character varying(255) NOT NULL,
    first_name    character varying(50)  NOT NULL,
    is_active     boolean DEFAULT true   NOT NULL,
    last_name     character varying(50)  NOT NULL,
    password_hash character varying(255) NOT NULL,
    role_id       integer
);

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_log_types
    ADD CONSTRAINT audit_log_types_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.generated_paysafe
    ADD CONSTRAINT generated_paysafe_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.paysafe_log
    ADD CONSTRAINT paysafe_log_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.paysafe_states
    ADD CONSTRAINT paysafe_states_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transaction_logs
    ADD CONSTRAINT transaction_logs_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.transaction_states
    ADD CONSTRAINT transaction_states_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.generated_paysafe
    ADD CONSTRAINT uk6pcc9vv7vucatp8gtnj6unlx4 UNIQUE (paysafe_number_hash);

ALTER TABLE ONLY public.paysafe_states
    ADD CONSTRAINT ukghelg3h0ybifavbea34i8anb0 UNIQUE (state);

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT ukktpif54u9a3ssn6rpxxqx6jvp UNIQUE (name);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);

ALTER TABLE ONLY public.transaction_states
    ADD CONSTRAINT ukom17fhmek9eqneiqd98ghyov9 UNIQUE (state);

ALTER TABLE ONLY public.audit_log_types
    ADD CONSTRAINT ukquxy2xv2etudc51vg0e2l3rsk UNIQUE (type);

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_pkey PRIMARY KEY (achievement_id, user_uuid);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (uuid);

ALTER TABLE ONLY public.transaction_logs
    ADD CONSTRAINT fk3q4gnojeoxcd4vowk6mdp3h8c FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);

ALTER TABLE ONLY public.paysafe_log
    ADD CONSTRAINT fk4wn8570mbw4vjqvt865kn5sao FOREIGN KEY (generated_paysafe_uuid) REFERENCES public.generated_paysafe(uuid);

ALTER TABLE ONLY public.paysafe_log
    ADD CONSTRAINT fk5y2tut6m50gtbv1kpc3jag4h8 FOREIGN KEY (new_paysafe_state) REFERENCES public.paysafe_states(id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk8cqa9a6ikygg3375jkm628y2l FOREIGN KEY (users_uuid) REFERENCES public.users(uuid);

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT fk8ipvec6cs8t3g8515thtlsxuf FOREIGN KEY (achievement_id) REFERENCES public.achievements(id);

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk8sfwuumifl0n0sxa078d21c3n FOREIGN KEY (audit_log_type_id) REFERENCES public.audit_log_types(id);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkalctbqhn1dci9s07syg122et7 FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkc9egln7f964n9fxtemrxck1eh FOREIGN KEY (generated_paysafe_uuid) REFERENCES public.generated_paysafe(uuid);

ALTER TABLE ONLY public.transaction_logs
    ADD CONSTRAINT fkhxwif0wmn994xx49s4iwevc6x FOREIGN KEY (new_transaction_state_id) REFERENCES public.transaction_states(id);

ALTER TABLE ONLY public.generated_paysafe
    ADD CONSTRAINT fkjhmws6qcepya74lx68e3h63mu FOREIGN KEY (paysafe_state_id) REFERENCES public.paysafe_states(id);

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT fkjurhx3aei5h653nkj5c8yxv5l FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);

ALTER TABLE ONLY public.transaction_logs
    ADD CONSTRAINT fkobwvan1lqk712gk0xpqilqtgu FOREIGN KEY (transaction_uuid) REFERENCES public.transactions(uuid);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.transaction_logs
    ADD CONSTRAINT fkqygtibrmxojbxbps0hq6e2qd3 FOREIGN KEY (old_transaction_state_id) REFERENCES public.transaction_states(id);

ALTER TABLE ONLY public.paysafe_log
    ADD CONSTRAINT fkragtmduwllrj4tmyuaro8epqs FOREIGN KEY (old_paysafe_state) REFERENCES public.paysafe_states(id);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fksa1b6f2upab17djgfmgles02p FOREIGN KEY (transaction_state_id) REFERENCES public.transaction_states(id);

ALTER TABLE ONLY public.paysafe_log
    ADD CONSTRAINT fktglx25q4ak0insp3wuikbbt06 FOREIGN KEY (user_uuid) REFERENCES public.users(uuid);